pentatrion_vite:
    public_directory: public
    build_directory: build
    throw_on_missing_entry: false
    throw_on_missing_asset: false
    builds:
        default:
            build_directory: build
