version: "3.8"

name: my_project

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    expose:
      - "9000"
    networks: [connectPerso]

  front:
    build:
      context: ./front
    working_dir: /app
    volumes:
      - ./front:/app:cached
    ports:
      - "5173:5173"
    command: npm run dev:dock
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
    networks: [connectPerso]

  # (optionnel) front-build pour produire /public/build
  front-build:
    build:
      context: ./front
    working_dir: /app
    volumes:
      - ./front:/app
      - ./public/build:/app/../public/build
    command: npm run build
    networks: [connectPerso]

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    depends_on:
      - php
      - front    # <— important si Nginx proxifie Vite
    volumes:
      - .:/var/www/symfony
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # <— configuration nginx
    networks: [connectPerso]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courTotal
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [connectPerso]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks: [connectPerso]

networks:
  connectPerso:
    driver: bridge

volumes:
  mysql_data:
