parameters:
    app.url: 'http://localhost:8080'

services:
    App\Doctrine\PrefixedNamingStrategy:
        arguments:
            $prefix: 'appy_'
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Doctrine/'

    # Listener pour nettoyer automatiquement les anciennes visites
    App\EventListener\UserPageVisitListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
